#!usr/bin/python

DEVICE_INFO = {
    'device_id' : 'YOUR_DEVICE_ID',
    'device_key' : 'YOUR_DEVICE_KEY'
}

# change 'INFO' to 'WARNING' to filter info messages
logging.basicConfig(level='INFO')

def establishCommandChannel():
# Query command server's IP & port
connectionAPI = 'https://api.mediatek.com/mcs/v2/devices/%(device_id)s/connections.csv'
r = requests.get(connectionAPI % DEVICE_INFO,
    headers = {'deviceKey' : DEVICE_INFO['device_key'],
        'Content-Type' : 'text/csv'})
logging.info("Command Channel IP,port=" + r.text)
(ip, port) = r.text.split(',')

# Connect to command server
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((ip, int(port)))
s.settimeout(None)
